### ISSUE TITLE
XInput Injector not able to attach to processes

### ISSUE THREAD

**Issue by qdot** [metafetish/buttplug-csharp#247]
```
2017-08-22 21:50:21.4110|INFO|Buttplug.Apps.XInputInjector.GUI.MainWindow|Beginning process injection on 2728...
2017-08-22 21:50:21.4110|ERROR|Buttplug.Apps.XInputInjector.GUI.MainWindow|System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at EasyHook.WOW64Bypass.Install()
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, InjectionOptions InOptions, String InLibraryPath_x86, String InLibraryPath_x64, Object[] InPassThruArgs)
   at Buttplug.Apps.XInputInjector.GUI.MainWindow.OnAttachRequested(Object aObject, Int32 aProcessId)
```

**Comment by qdot** [comment]
Forgot to copy EasyHook*Srv.exe files when building the installer.

**Comment by qdot** [comment]
https://sentry.io/metafetish/buttplug-csharp/issues/333674478/
