### ISSUE TITLE
Intermittent GUI Bringup test failure with WebSocketServer on Appveyor due to SSL cert

### ISSUE THREAD

**Issue by qdot** [metafetish/buttplug-csharp#277]
https://ci.appveyor.com/project/qdot/buttplug-csharp/build/0.1.0.479

Stack:
```
xecuting: C:\Tools\xUnit20\xunit.console.x86.exe
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Buttplug.Server.Test
  Discovered:  Buttplug.Server.Test
  Starting:    Buttplug.Server.Test
  Finished:    Buttplug.Server.Test
  Discovering: Buttplug.Client.Test
  Discovered:  Buttplug.Client.Test
  Starting:    Buttplug.Client.Test
  Finished:    Buttplug.Client.Test
  Discovering: Buttplug.Apps.WebsocketServerGUI.Test
  Discovered:  Buttplug.Apps.WebsocketServerGUI.Test
  Starting:    Buttplug.Apps.WebsocketServerGUI.Test
   Buttplug.Apps.WebsocketServerGUI.Test.ButtplugWebsocketServerGUITest.TestGUIBringup [FAIL]

At line:1 char:1
+ .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntarge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (    Buttplug.Ap...IBringup [FAIL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
  
     Bad Data.
      
   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
         at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 keyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)
         at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
         at Buttplug.Components.WebsocketServer.CertUtils.ToDotNetKey(RsaPrivateCrtKeyParameters privateKey) in C:\projects\buttplug-csharp\Buttplug.Components.WebsocketServer\CertUtils.cs:line 125
         at Buttplug.Components.WebsocketServer.CertUtils.GenerateSelfSignedCertificate(String subject, X509Certificate2 issuer, AsymmetricCipherKeyPair issuerKeyPair) in C:\projects\buttplug-csharp\Buttplug.Components.WebsocketServer\CertUtils.cs:line 101
         at Buttplug.Components.WebsocketServer.CertUtils.GetCert(String app, String hostname) in C:\projects\buttplug-csharp\Buttplug.Components.WebsocketServer\CertUtils.cs:line 193
         at Buttplug.Components.WebsocketServer.ButtplugWebsocketServer.StartServer(IButtplugServerFactory aFactory, Int32 aPort, Boolean aLoopBack, Boolean aSecure, String aHostname) in C:\projects\buttplug-csharp\Buttplug.Components.WebsocketServer\ButtplugWebsocketServer.cs:line 63
         at Buttplug.Apps.WebsocketServerGUI.WebsocketServerControl.StartServer() in C:\projects\buttplug-csharp\Buttplug.Apps.WebsocketServerGUI\WebsocketServerControl.xaml.cs:line 151
         at Buttplug.Apps.WebsocketServerGUI.MainWindow..ctor() in C:\projects\buttplug-csharp\Buttplug.Apps.WebsocketServerGUI\MainWindow.xaml.cs:line 35
         at Buttplug.Apps.WebsocketServerGUI.Test.ButtplugWebsocketServerGUITest.StartGUI() in C:\projects\buttplug-csharp\Buttplug.Apps.WebsocketServerGUI.Test\ButtplugWebsocketServerGUITest.cs:line 32

```

**Comment by blackspherefollower** [comment]
This looks like the same error as #271 but in English

**Comment by qdot** [comment]
https://sentry.io/metafetish/buttplug-csharp/issues/439034027/
