### ISSUE TITLE
Update checks not working from Websocket Server App

### ISSUE THREAD

**Issue by qdot** [metafetish/buttplug-csharp#355]
When checking for updates from the Websocket Server application, we get the following error.

```
018-02-28 12:52:23.4704|INFO|Buttplug.Components.Controls.ButtplugTabControl|Buttplug Server Revision: 0.2.0 e5e3e81f50daa72f9e11af32ec44cef3e85f6142
2018-02-28 12:52:23.4824|INFO|Buttplug.Components.Controls.ButtplugTabControl|Windows Release ID: 1709
2018-02-28 12:52:23.9265|ERROR|ButtplugAboutControl|System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send.
   at System.Net.HttpWebRequest.GetResponse()
   at Buttplug.Components.Controls.ButtplugAboutControl.CheckForUpdates_Click(Object sender, RoutedEventArgs e)
```

This happens from both v0.1.2 and v0.2.0, meaning it could be some sort of server/TLS issue

**Comment by qdot** [comment]
This has to do with our hosting. Specifically:

> As of January 29th 2018, DreamHost will no longer support TLS 1.0 on its web servers. If you're still using a browser that is only able to connect using TLS 1.0, you will not be able to view websites hosted at DreamHost using HTTPS. This means any site using an SSL certificate.

So, we need to do two things:

- Add the following line to the Websocket server:

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;
```

- Move updates.buttplug.io to a server that will support TLS 1.0 until we can run the next update cycle and fix this.

Weirdly enough, updates still work in the GVR. Checking the value of ServicePointManager.SecurityProtocol there, it shows up at

```
Tls | Tls11 | Tls12
```
Most likely, this means that one of the libraries the WebSocketServer depends on for building the server portion is changing the SecurityProtocol for the whole app domain.

**Comment by qdot** [comment]
This boils down to a .Net framework versioning problem. The Websocket and Kiiroo server apps are both build using .Net 4.5.2, which was the default at the time I started working on them. The GVR came along later, and is built on .Net 4.6.1. The default Security protocol set in 4.5.2 is TLS1/SSL3, while in 4.6 it's TLS1/TLS1.1/TLS1.2. Since Dreamhost changed the minimum TLS version they support, that's why things work in the GVR but not in the other two apps.

**Comment by qdot** [comment]
buttplug.io domain moved to S3/Cloudfront, and updates domain set back to TLS1. This seems to make it work in 0.1.2/0.2.0 app suite applications again.
